# version: "3"
services:

  app:
    image: happy
    container_name: happy_container
    ports:
      - "5000:5000"
    depends_on:
      -   postgre
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # networks:
    #   app_network: 
    #     ipv4_address: "123.23.23.2"

  postgre:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: happy_user
      POSTGRES_PASSWORD: happy
      POSTGRES_DB: happy_db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./happy_pgdata:/var/lib/postgresql/data
    # networks:
    #   app_network: 
    #     ipv4_address: "123.23.23.4"

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: postgre-service_default

# networks:
#   app_network:
#     ipam:
#       driver: default