version: "3"
services:

  app:
    image: happy
    ports:
      - "5000:5000"
    depends_on:
      - db
    # volumes:
    #   - ./flask:/app/uploads
    # networks:
    #   app_network: 
    #     ipv4_address: "123.23.23.2"
    command: /bin/bash

  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    # volumes:
    #   - ./postgreSQL:/var/lib/postgresql/data
    # networks:
    #   app_network: 
    #     ipv4_address: "123.23.23.4"


# networks:
#   app_network:
#     ipam:
#       driver: default