# version: "3"
services:

  app:
    image: happy
    container_name: happy_container
    ports:
      - 5000:5000
    depends_on:
      - postgre
    volumes:
      - .:/app
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  postgre:
    image: happy_db
    container_name: postgres_container
    environment:
      POSTGRES_USER: happy_user
      POSTGRES_PASSWORD: happy
      POSTGRES_DB: happy_db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./happy_pgdata:/var/lib/postgresql/data

  task:
    image: happy
    container_name: task_container
    depends_on:
      - postgre
    ports:
      - 8888:8888
    volumes:
      - .:/app
    command: [python, ./handle_dataset.py]
    # environment:
    #   NVIDIA_VISIBLE_DEVICES: all
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: postgre-service_default
